# Generated by Django 3.1.2 on 2020-10-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrafirma', '0001_initial'),
        ('terrafirma_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockSale',
            new_name='StoreSale',
        ),
    ]
