# Generated by Django 3.1.2 on 2020-10-03 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('short_name', models.CharField(max_length=16)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('short_name', models.CharField(max_length=16)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaladyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name_plural': 'maladies',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('text_md5', models.CharField(default=django.db.models.functions.text.MD5('text'), max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('s', 'seeds'), ('r', 'rows')], max_length=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=64)),
                ('variety', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Transplanting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bed')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.planttype'),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.bed')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.environment')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.plant')),
                ('plant_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.planttype')),
                ('text', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.note')),
            ],
        ),
        migrations.CreateModel(
            name='Malady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bed')),
                ('details', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.note')),
                ('malady', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.maladytype')),
                ('sowing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True)),
                ('unit', models.CharField(choices=[('g', 'grams'), ('c', 'count')], max_length=1)),
                ('in_stock', models.BooleanField(default=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plant')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.environment'),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('observation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.observation')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.treatmenttype')),
            ],
            bases=('core.observation',),
        ),
    ]
