# Generated by Django 3.1.2 on 2020-10-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrafirma', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transplanting',
            constraint=models.UniqueConstraint(condition=models.Q(active=True), fields=('plant',), name='unique_active'),
        ),
    ]
