# Generated by Django 3.1.2 on 2020-10-18 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrafirma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='plants',
                                    to='terrafirma.planttype'),
        ),
    ]
