# Generated by Django 3.1.2 on 2020-10-04 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrafirma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='short_name',
        ),
        migrations.AddField(
            model_name='bed',
            name='long_name',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='environment',
            name='long_name',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bed',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='terrafirma.environment'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
