# Generated by Django 3.1.2 on 2020-10-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrafirma', '0002_auto_20201008_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='environment',
            new_name='env',
        ),
    ]
