# Generated by Django 3.1.2 on 2020-10-06 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrafirma', '0002_auto_20201004_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transplanting',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transplants', to='terrafirma.plant'),
        ),
    ]
