# Generated by Django 3.1.2 on 2020-10-08 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrafirma', '0003_auto_20201008_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='terrafirma.environment', verbose_name='environment'),
        ),
    ]
