# Generated by Django 3.1.2 on 2020-10-06 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrafirma', '0003_auto_20201006_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='transplanting',
            name='current',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transplanting',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transplants', to='terrafirma.bed'),
        ),
    ]
