# Generated by Django 3.1.2 on 2020-10-03 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrafirma', '0003_auto_20201003_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('sowing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terrafirma.sowing')),
            ],
        ),
        migrations.CreateModel(
            name='Malady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name_plural': 'maladies',
            },
        ),
        migrations.CreateModel(
            name='MaladyInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terrafirma.bed')),
                ('malady', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terrafirma.malady')),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.DeleteModel(
            name='Harvesting',
        ),
        migrations.DeleteModel(
            name='TreatmentType',
        ),
    ]
