# Generated by Django 3.1.2 on 2020-10-08 22:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrafirma', '0004_auto_20201008_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='abbrev',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[a-z\\-0-9]+\\Z', 'Only use lowercase a-z, numbers, and hyphens.')], verbose_name='abbreviation'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('name', 'env'), ('abbrev', 'env')},
        ),
    ]
