# Generated by Django 3.1.2 on 2020-10-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrafirma', '0004_auto_20201003_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentinstance',
            name='details',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
