# Generated by Django 3.1.2 on 2020-10-06 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrafirma', '0004_auto_20201006_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transplanting',
            old_name='current',
            new_name='active',
        ),
    ]
