# Generated by Django 3.1.2 on 2020-10-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrafirma', '0005_auto_20201008_2259'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planttype',
            unique_together={('common_name', 'variety')},
        ),
    ]
