# Generated by Django 3.1.2 on 2020-10-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrafirma', '0005_treatmentinstance_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentinstance',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
