# Generated by Django 3.1.2 on 2020-10-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrafirma', '0005_auto_20201006_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='beds',
            field=models.ManyToManyField(through='terrafirma.Transplanting', to='terrafirma.Bed'),
        ),
    ]
