# Generated by Django 3.1.2 on 2020-10-03 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrafirma', '0006_auto_20201003_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=64)),
                ('variety', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='sowing',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='sowing',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='common_name',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='variety',
        ),
        migrations.RemoveField(
            model_name='transplanting',
            name='sowing',
        ),
        migrations.AddField(
            model_name='harvest',
            name='plant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='terrafirma.plant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observation',
            name='plant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='terrafirma.plant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='number',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='unit',
            field=models.CharField(choices=[('s', 'seeds'), ('r', 'rows')], default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transplanting',
            name='plant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='terrafirma.plant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentinstance',
            name='sowing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='terrafirma.plant'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sowing',
        ),
        migrations.AddField(
            model_name='plant',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='terrafirma.planttype'),
            preserve_default=False,
        ),
    ]
