# Generated by Django 3.1.2 on 2020-10-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrafirma', '0006_auto_20201009_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transplanting',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
