# Generated by Django 3.1.2 on 2020-10-10 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrafirma', '0007_auto_20201010_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='cur_transplant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='terrafirma.transplanting'),
        ),
    ]
